"""Apply numbered SQL migrations from backend/models/migrations/.

    python scripts/migrate.py up --dsn postgresql://...      apply what is pending
    python scripts/migrate.py status --dsn ...               what is applied, what is pending
    python scripts/migrate.py snapshot [--check]             write or verify backend/models/schema.sql

Files are named `NNNN_description.sql` and run in number order, each in its own transaction, so
a failing migration leaves the database at the previous one. Applied versions are recorded in
`schema_migrations` with a checksum; editing an applied file is an error (write a new migration).
A session advisory lock stops two runners from racing. `schema.sql` is the concatenation of all
migrations, kept in sync by `snapshot` and checked by a test.
"""
from __future__ import annotations

import argparse
import asyncio
import hashlib
import os
import re
import sys
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

MIGRATIONS_DIR = Path(__file__).resolve().parents[1] / "backend" / "models" / "migrations"
SCHEMA_SNAPSHOT = MIGRATIONS_DIR.parent / "schema.sql"
NAME = re.compile(r"^(\d{4})_[a-z0-9_]+\.sql$")
LOCK_KEY = 7_262_026  # arbitrary, only has to be the same in every runner

SNAPSHOT_HEADER = (
    "-- GENERATED by `python scripts/migrate.py snapshot` from backend/models/migrations/. Do not edit.\n"
    "-- Change the schema by adding a numbered migration, then regenerate this file.\n"
)

CREATE_TABLE = """
CREATE TABLE IF NOT EXISTS schema_migrations (
    version     INTEGER PRIMARY KEY,
    name        TEXT NOT NULL,
    checksum    TEXT NOT NULL,
    applied_at  TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""


class MigrationError(RuntimeError):
    pass


@dataclass(frozen=True)
class Migration:
    version: int
    name: str
    sql: str
    checksum: str


def discover(directory: Path = MIGRATIONS_DIR) -> list[Migration]:
    found: list[Migration] = []
    for path in sorted(directory.glob("*.sql")):
        match = NAME.match(path.name)
        if not match:
            raise MigrationError(f"{path.name}: migration files are named NNNN_description.sql (lowercase, digits, underscores)")
        sql = path.read_text(encoding="utf-8")
        found.append(Migration(int(match.group(1)), path.name, sql, hashlib.sha256(sql.encode()).hexdigest()))
    versions = [m.version for m in found]
    if len(set(versions)) != len(versions):
        raise MigrationError("two migration files share a version number")
    if versions != list(range(1, len(versions) + 1)):
        raise MigrationError(f"migration numbers must run 1..N without gaps, found {versions}")
    return found


def snapshot(migrations: Sequence[Migration]) -> str:
    parts = [SNAPSHOT_HEADER]
    for migration in migrations:
        parts.append(f"\n-- ---- {migration.name} ----\n{migration.sql.rstrip(chr(10))}\n")
    return "".join(parts)


async def applied_versions(connection: Any) -> dict[int, str]:
    await connection.execute(CREATE_TABLE)
    rows = await connection.fetch("SELECT version, checksum FROM schema_migrations ORDER BY version")
    return {row["version"]: row["checksum"] for row in rows}


def pending(migrations: Sequence[Migration], applied: dict[int, str]) -> list[Migration]:
    for migration in migrations:
        if migration.version in applied and applied[migration.version] != migration.checksum:
            raise MigrationError(f"{migration.name} was edited after it was applied. Revert the edit and add a new migration.")
    unknown = set(applied) - {m.version for m in migrations}
    if unknown:
        raise MigrationError(f"the database has migrations this checkout does not: {sorted(unknown)}")
    return [m for m in migrations if m.version not in applied]


async def migrate(connection: Any, migrations: Sequence[Migration] | None = None) -> list[str]:
    """Apply pending migrations. Returns the names applied, in order."""
    migrations = discover() if migrations is None else migrations
    await connection.execute("SELECT pg_advisory_lock($1)", LOCK_KEY)
    try:
        todo = pending(migrations, await applied_versions(connection))
        done: list[str] = []
        for migration in todo:
            async with connection.transaction():
                await connection.execute(migration.sql)
                await connection.execute(
                    "INSERT INTO schema_migrations (version, name, checksum) VALUES ($1, $2, $3)",
                    migration.version, migration.name, migration.checksum,
                )
            done.append(migration.name)
        return done
    finally:
        await connection.execute("SELECT pg_advisory_unlock($1)", LOCK_KEY)


async def run_migrations(dsn: str) -> list[str]:
    """For services that migrate on start (ingestion)."""
    import asyncpg

    connection = await asyncpg.connect(dsn)
    try:
        return await migrate(connection)
    finally:
        await connection.close()


async def _status(dsn: str) -> int:
    import asyncpg

    connection = await asyncpg.connect(dsn)
    try:
        migrations = discover()
        applied = await applied_versions(connection)
        todo = {m.version for m in pending(migrations, applied)}
    finally:
        await connection.close()
    for migration in migrations:
        print(f"{'pending' if migration.version in todo else 'applied':8} {migration.name}")
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("command", choices=["up", "status", "snapshot"])
    parser.add_argument("--dsn", default=os.environ.get("POSTGRES_DSN"))
    parser.add_argument("--check", action="store_true", help="snapshot: fail if schema.sql is out of date instead of writing it")
    args = parser.parse_args(argv)
    try:
        if args.command == "snapshot":
            text = snapshot(discover())
            if args.check:
                if not SCHEMA_SNAPSHOT.exists() or SCHEMA_SNAPSHOT.read_text(encoding="utf-8") != text:
                    print("schema.sql is out of date; run: python scripts/migrate.py snapshot", file=sys.stderr)
                    return 1
                print("schema.sql is up to date")
                return 0
            SCHEMA_SNAPSHOT.write_text(text, encoding="utf-8")
            print(f"wrote {SCHEMA_SNAPSHOT}")
            return 0
        if not args.dsn:
            parser.error("--dsn is required (or set POSTGRES_DSN)")
        if args.command == "status":
            return asyncio.run(_status(args.dsn))
        applied = asyncio.run(run_migrations(args.dsn))
        print("applied: " + (", ".join(applied) if applied else "nothing, already up to date"))
        return 0
    except MigrationError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
